from .BoolObject import BoolObject
from .FloatObject import FloatObject
from .IntObject import IntObject
from .NilObject import NilObject
from .StringObject import StringObject
from .VarObject import VarObject
from .FuncObject import FuncObject
from .ArrayObject import ArrayObject
from .ClassObject import ClassObject
